// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentManagement.Data;

#nullable disable

namespace ShipmentManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328112759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShipmentManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateCountry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mumbai",
                            CompanyName = "Reliance Industries",
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2340),
                            CustomerCode = "C001",
                            CustomerName = "Rajesh Mehta",
                            Email = "r.mehta@reliance.com",
                            Phone = "+91 98765 43210"
                        },
                        new
                        {
                            Id = 2,
                            City = "Jamshedpur",
                            CompanyName = "Tata Steel",
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2347),
                            CustomerCode = "C002",
                            CustomerName = "Anita Sharma",
                            Email = "anita.s@tatasteel.com",
                            Phone = "+91 87654 32109"
                        },
                        new
                        {
                            Id = 3,
                            City = "Dehradun",
                            CompanyName = "ONGC",
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2350),
                            CustomerCode = "C003",
                            CustomerName = "Vikram Nair",
                            Email = "v.nair@ongc.in",
                            Phone = "+91 76543 21098"
                        },
                        new
                        {
                            Id = 4,
                            City = "Ahmedabad",
                            CompanyName = "Adani Ports",
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2352),
                            CustomerCode = "C004",
                            CustomerName = "Priya Desai",
                            Email = "p.desai@adani.com",
                            Phone = "+91 65432 10987"
                        },
                        new
                        {
                            Id = 5,
                            City = "Chennai",
                            CompanyName = "L&T Shipping",
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2355),
                            CustomerCode = "C005",
                            CustomerName = "Suresh Kumar",
                            Email = "s.kumar@lt.com",
                            Phone = "+91 54321 09876"
                        });
                });

            modelBuilder.Entity("ShipmentManagement.Models.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PortCode")
                        .IsUnique();

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mumbai",
                            Country = "India",
                            IsActive = true,
                            PortCode = "INBOM",
                            PortName = "Mumbai Port"
                        },
                        new
                        {
                            Id = 2,
                            City = "Navi Mumbai",
                            Country = "India",
                            IsActive = true,
                            PortCode = "INJNP",
                            PortName = "JNPT Port"
                        },
                        new
                        {
                            Id = 3,
                            City = "Chennai",
                            Country = "India",
                            IsActive = true,
                            PortCode = "INMAA",
                            PortName = "Chennai Port"
                        },
                        new
                        {
                            Id = 4,
                            City = "Kandla",
                            Country = "India",
                            IsActive = true,
                            PortCode = "INKND",
                            PortName = "Kandla Port"
                        },
                        new
                        {
                            Id = 5,
                            City = "Dubai",
                            Country = "UAE",
                            IsActive = true,
                            PortCode = "AEJEA",
                            PortName = "Jebel Ali Dubai"
                        },
                        new
                        {
                            Id = 6,
                            City = "Singapore",
                            Country = "Singapore",
                            IsActive = true,
                            PortCode = "SGSIN",
                            PortName = "Singapore PSA"
                        },
                        new
                        {
                            Id = 7,
                            City = "Rotterdam",
                            Country = "Netherlands",
                            IsActive = true,
                            PortCode = "NLRTM",
                            PortName = "Port of Rotterdam"
                        });
                });

            modelBuilder.Entity("ShipmentManagement.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityMT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.HasIndex("ShipCode")
                        .IsUnique();

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityMT = 52000m,
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2069),
                            FlagCountry = "India",
                            ImoNumber = "9876543",
                            ShipCode = "S001",
                            ShipName = "MV Titan",
                            ShipType = "Bulk Carrier",
                            Status = 0,
                            YearBuilt = 2018
                        },
                        new
                        {
                            Id = 2,
                            CapacityMT = 38000m,
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2096),
                            FlagCountry = "India",
                            ImoNumber = "9765432",
                            ShipCode = "S002",
                            ShipName = "MV Neptune",
                            ShipType = "Container",
                            Status = 0,
                            YearBuilt = 2020
                        },
                        new
                        {
                            Id = 3,
                            CapacityMT = 65000m,
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2100),
                            FlagCountry = "Singapore",
                            ImoNumber = "9654321",
                            ShipCode = "S003",
                            ShipName = "MV Horizon",
                            ShipType = "Tanker",
                            Status = 0,
                            YearBuilt = 2016
                        },
                        new
                        {
                            Id = 4,
                            CapacityMT = 28500m,
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2103),
                            FlagCountry = "UK",
                            ImoNumber = "9543210",
                            ShipCode = "S004",
                            ShipName = "MV Orion",
                            ShipType = "Cargo",
                            Status = 0,
                            YearBuilt = 2019
                        },
                        new
                        {
                            Id = 5,
                            CapacityMT = 71000m,
                            CreatedAt = new DateTime(2026, 3, 28, 16, 57, 56, 860, DateTimeKind.Local).AddTicks(2106),
                            FlagCountry = "India",
                            ImoNumber = "9432109",
                            ShipCode = "S005",
                            ShipName = "MV Atlas",
                            ShipType = "Bulk Carrier",
                            Status = 0,
                            YearBuilt = 2015
                        });
                });

            modelBuilder.Entity("ShipmentManagement.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CargoType")
                        .HasColumnType("int");

                    b.Property<string>("ContainerNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShipmentType")
                        .HasColumnType("int");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightMT")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShipId");

                    b.HasIndex("ShipmentCode")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShipmentManagement.Models.ShipmentStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentStatusLogs");
                });

            modelBuilder.Entity("ShipmentManagement.Models.ShipmentTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StepDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StepLocation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("StepStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentTrackings");
                });

            modelBuilder.Entity("ShipmentManagement.Models.Shipment", b =>
                {
                    b.HasOne("ShipmentManagement.Models.Customer", "Customer")
                        .WithMany("Shipments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipmentManagement.Models.Ship", "Ship")
                        .WithMany("Shipments")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipmentManagement.Models.ShipmentStatusLog", b =>
                {
                    b.HasOne("ShipmentManagement.Models.Shipment", "Shipment")
                        .WithMany("StatusLogs")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentManagement.Models.ShipmentTracking", b =>
                {
                    b.HasOne("ShipmentManagement.Models.Shipment", "Shipment")
                        .WithMany("TrackingSteps")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentManagement.Models.Customer", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ShipmentManagement.Models.Ship", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ShipmentManagement.Models.Shipment", b =>
                {
                    b.Navigation("StatusLogs");

                    b.Navigation("TrackingSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
